name: Run Operator Unit Tests

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
  KUBERNETES_VERSION: "v1.22.2"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Deploy Dependencies
        id: deploy
        run: |
          bash .travis/install-tools.sh
          bash .travis/install-python.sh
          sudo bash .travis/install-minikube.sh

      # - name: Run Generate API
      #   id: run-gen-api
      #   run: make gen-api-fail-if-dirty --always-make || exit 1

      # - name: Run Build
      #   id: run-build
      #   run: make build || exit 1

      # - name: Run Test
      #   id: run-test
      #   run: make test || exit 1

      - name: Run Test OLM
        id: run-test-olm
        run: |
          go version
          sudo env "PATH=$PATH" make test-olm || exit 1
